### ISSUE TITLE
HERB sim rosinstall?

### ISSUE THREAD

**Issue by siddhss5** [personalrobotics/pr-rosinstalls#3]
It'd be fantastic to have a herb-sim rosinstall, which I think would be a pared-down version of [herb-minimal-remote-op.rosinstall] (https://github.com/personalrobotics/pr-rosinstalls/blob/master/herb-minimal-remote-op.rosinstall), no?

**Comment by jeking04** [comment]
I believe I have this in the herbpy README:

https://github.com/personalrobotics/herbpy

I can move it to the install repo.

On Thu, Aug 6, 2015 at 10:31 AM, Siddhartha Srinivasa <
notifications@github.com> wrote:

> It'd be fantastic to have a herb-sim rosinstall, which I think would be a
> pared-down version of herb-minimal-remote-op.rosinstall, no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/personalrobotics/pr-rosinstalls/issues/3>.
>



-- 
Jen King

**Comment by mkoval** [comment]
I copied the `.rosinstall` file from the HerbPy README over to this repository in cf2561355da4dd5f168cdb75d99990fdd8d456df.
